// app/layout.js
import "@/app/globals.css";
import NavBar from "@/components/NavBar";
import Footer from "@/components/Footer";
import { NextUIProvider } from "@nextui-org/react";
import { Toaster } from "react-hot-toast";

export const metadata = {
  title: "InstaHandi",
  description: "Generated by InstaHandi",
};

export default function Layout({ children }) {
  return (
    <main>
      <NavBar />
      {children}
      <Footer />
    </main>
  );
}
