// app/layout.js
import "@/app/globals.css";
import NavBar from "@/components/NavBar";
import Footer from "@/components/Footer";
import { NextUIProvider } from "@nextui-org/react";
import { Toaster } from "react-hot-toast";
import { cookies } from "next/headers";

export const metadata = {
  title: "InstaHandi",
  description: "Generated by InstaHandi",
};

export default async function Layout({ children }) {
  const cookieStore = await cookies();
  const userRole = await cookieStore.get("userRole")?.value || null;
  const authToken = await cookieStore.get("authToken")?.value || null;
  return (
    <main>
      <NavBar userRole={userRole} authToken={authToken} />
      {children}
      <Footer />
    </main>
  );
}
