// app/layout.js
import "@/app/globals.css";
import NavBar from "@/components/NavBar";
import Footer from "@/components/Footer";
import { NextUIProvider } from "@nextui-org/react";
import { Toaster } from "react-hot-toast";

export const metadata = {
  title: "InstaHandi",
  description: "Generated by InstaHandi",
};

export default function RootLayout({ children }) {
  
  return (
    <html lang="en">
      <head>
        <link
          href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;600;700&display=swap"
          rel="stylesheet"
        />
      </head>
      <body className="antialiased">
        <NextUIProvider>
          <main className="purple-dark text-foreground bg-background">
            {children}
            <Toaster position="top-right" reverseOrder={false} />
          </main>
        </NextUIProvider>
      </body>
    </html>
  );
}
